spring:
  application:
    name: ribbon-loadbalancer
server:
  port: 6616

eureka:
  client:
    service-url:
      defaultZone: http://localhost:1111/eureka/
  instance:
    prefer-ip-address: true

#email-provider:
#  ribbon:
#    ConnectTimeout: 3000
#    ReadTimeout: 60000
#    MaxAutoRetries: 1 #对第一次请求的服务的重试次数
#    MaxAutoRetriesNextServer: 1 #要重试的下一个服务的最大数量（不包括第一个服务）
#    OkToRetryOnAllOperations: true
#    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule
#ribbon:
#  eager-load:
#    enabled: true # 开启饥饿模式
#    clients: email-provider # 多个以逗号分隔