server:
  port: 8082
  servlet:
    context-path: /
mybatis:
  type-aliases-package: com.javen.model
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      url: jdbc:mysql://localhost:3306/test?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8&useSSL=true
      username: root
      password: Ub1KM73u64YRWUnXZXe/5XhRwFaWxvx646Y0weLL6CiaHTJm0B0ilW0mup2bLXoI6qN0JowCC+TqCFXHKrv94A==
      driver-class-name: com.mysql.cj.jdbc.Driver
      #初始化连接大小
      initial-size: 6
      #最小接数
      min-idle: 6
      #最大连接数
      max-active: 10
      #配置获取连接等待超时的时间
      max-wait: 80000
      # 监控后台账号和密码
      stat-view-servlet:
        login-username: IJPay
        login-password: 123456
      filters: stat,config
      # 配置 StatFilter
      filter:
        stat:
          # 打印慢sql
          log-slow-sql: true
          # 超过3000毫秒即为慢sql
          slow-sql-millis: 3000
