server:
  port: 8081
  servlet:
    context-path: /
mybatis:
  type-aliases-package: com.javen.model
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8&useSSL=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      #初始化连接大小
      initial-size: 6
      #最小接数
      min-idle: 6
      #最大连接数
      max-active: 10
      #配置获取连接等待超时的时间
      max-wait: 80000
      # 监控后台账号和密码
      stat-view-servlet:
        login-username: IJPay
        login-password: 123456
      # 配置 StatFilter
      filter:
        stat:
          # 打印慢sql
          log-slow-sql: true
          # 超过3000毫秒即为慢sql
          slow-sql-millis: 3000
