server:
  port: 1111

spring:
  application:
    name: eureka-server
eureka:
  instance:
    hostname: localhost
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://localhost:1111/eureka/ # one eureka server
      #defaultZone: http://localhost:1112/eureka/ # two eureka server
      #defaultZone: http://localhost:1112/eureka/,http://localhost:1113/eureka/ # three eureka server
    register-with-eureka: true
    fetch-registry: true
  server:
    registry-sync-retry-wait-ms: 0
    enable-self-preservation: false
management:
  endpoints:
    web:
      exposure:
        include: refresh,health # 或者 '*'
