server:
  port: 8011
spring:
  application:
    name: email-consumer

eureka:
  client:
    service-url:
      defaultZone: http://localhost:1111/eureka/
#feign:
#  client:
#    config:
#      default:
#        connectTimeout: 60000
#        readTimeOut: 60000
#        loggerLevel: basic

